panjrathJashanjotA1: panjrathJashanjotA1.o panjrathJashanjotA1Main.o
	gcc -Wall -std=c99 panjrathJashanjotA1.o panjrathJashanjotA1Main.o -o panjrathJashanjotA1
panjrathJashanjotA1.o: panjrathJashanjotA1.c givenA1.h
	gcc -Wall -std=c99 -c panjrathJashanjotA1.c
panjrathJashanjotA1Main.o: panjrathJashanjotA1Main.c givenA1.h
	gcc -Wall -std=c99 -c panjrathJashanjotA1Main.c
clean:
	rm *.o panjrathJashanjotA1
